### ISSUE TITLE
Efficient copying of data to GPU

### ISSUE THREAD

**Issue by tambetm** [NervanaSystems/neon#103]
I'm using `Model.fprop()` to implement prediction in my application. The problem is, that `fprop()` expects the batch size dimension (number of samples) to be the last. I can certainly create a Numpy array that matches these expectations, but as I fill out my samples in batch one-by-one, when using C-ordered array, filling out the Numpy matrix is quite slow (because of non-contiguous memory).

```
from neon.util.argparser import NeonArgparser
from neon.backends import gen_backend
import numpy as np

parser = NeonArgparser()
args = parser.parse_args()

be = gen_backend(backend=args.backend,
                 batch_size=32,
                 rng_seed=args.rng_seed,
                 device_id=args.device_id,
                 default_dtype=args.datatype,
                 stochastic_round=False)

tensor = be.empty((4,84,84,32))

# works, but filling minibatch is slow
matrix = np.empty((4,84,84,32))
for i in xrange(32):
  matrix[...,i] = np.zeros((4,84,84)) # more complicated logic here
tensor.set(matrix)
```

I can use batch size dimension as first in Numpy matrix and permute dimensions when assigning to Neon tensor, but this gives an error:
```
# does not work
matrix = np.zeros((32,4,84,84))
tensor.set(np.transpose(matrix, axes = (1, 2, 3, 0)))

Traceback (most recent call last):
  File "test.py", line 32, in <module>
    tensor.set(np.transpose(matrix, axes = (1, 2, 3, 0)))
  File "/home/tambet/neon_new/neon/backends/nervanagpu.py", line 378, in set
    self.dtype.itemsize * s for s in self.strides)
AssertionError
```

If I make copy before assigning the permuted matrix, it works:
```
# works, but unnecessary copy
matrix = np.zeros((32,4,84,84))
tensor.set(np.transpose(matrix, axes = (1, 2, 3, 0)).copy())
```

I also tried to match the dimensions of tensor and use F-ordering in my matrix, so that filling it is still efficient. Unfortunately that didn't help:
```
# fast filling of minibatch, but does not work either
matrix = np.zeros((4,84,84,32), order='F')
tensor.set(matrix)

Traceback (most recent call last):
  File "test.py", line 36, in <module>
    tensor.set(matrix)
  File "/home/tambet/neon_new/neon/backends/nervanagpu.py", line 378, in set
    self.dtype.itemsize * s for s in self.strides)
AssertionError
```

Is there a way to use efficient Numpy array layout in my case and avoid copying of the array? Why `fprop()` has the batch_size as last dimension anyway, when Neon is using C-ordered arrays?

BTW, I'm using Neon to implement DeepMind's deep Q-learning algorithm. It already learns simple games like Pong, but not on par with DeepMind's results yet. I take a pride in the very compact code, and also hope to make it fast thanks to Neon. See https://github.com/tambetm/simple_dqn.

**Comment by apark263** [comment]
Fastest way to handle this is to transfer the batchsize major host (numpy)
array directly onto gpu with the same memory layout and then perform the
transpose on gpu, which will be much faster using the element wise
transpose kernel.

h_a = np.empty((N, M))

d_a = be.empty((N, M))
d_aT = be.empty((M, N))

d_a.set(h_a)  # host to device transfer
d_aT[:] = d_a.T  # device to device transpose

If you are using the cpu backend you won't see any benefit, in fact it will
probably be slower than another cpu implementation you may be using.

The reason we use batchsize minor ordering in neon is because it has
superior memory locality for convolution and for concatenation along
feature map dimensions.  From our perspective, the cpu backend is purely
for prototyping and testing for correctness.
