### ISSUE TITLE
Systemwide installation doesn't copy GPU kernels into installation dir

### ISSUE THREAD

**Issue by buriy** [NervanaSystems/neon#117]
Systemwide installation doesn't put kernels into installation directory

And then we've got the following error:
```
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/nervanagpu.py", line 1170, in compound_dot
    kernel = kernel_specs.get_kernel("_".join((clss, op, size)))
  File "<string>", line 2, in get_kernel
  File "/usr/local/lib/python2.7/dist-packages/pycuda-2015.1-py2.7-linux-x86_64.egg/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/kernel_specs.py", line 431, in get_kernel
    module = drv.module_from_file(os.path.join(cubin_dir, kernel_name + ".cubin"))
pycuda._driver.RuntimeError: cuModuleLoad failed: file not found
```
This happens because it does check for GPU using nvcc search.
If compilation runs without sudo and nvcc is not set for root user, it gets wrong answer.
```python
gpuflag = os.system("nvcc --version > /dev/null 2>&1") == 0
if gpuflag:
    package_data = {'neon': ['backends/kernels/sass/*.sass',
                             'backends/kernels/cubin/*.cubin',
                             'data/*.so']}
else:
    package_data = {'neon': []}
```
What's wrong with always copying kernels if they were successfully built?

**Comment by scttl** [comment]
I think the condition was originally put in place as a guard to prevent warnings when none of the package_data paths could be found, something that could happen on systems without graphics cards for instance.  Since we distribute the .sass files now, these files will always be found, so you're right, it makes sense to remove this conditional.

I'll provide a patch shortly, but note that the user you install as will still need to have `nvcc` in their PATH to ensure the .cubin's get built, prior to being copied into the install dir.  Suppose you could build as non-root with a user with `nvcc`, and then separately run `sudo make sysinstall` after.

**Comment by buriy** [comment]
>Suppose you could build as non-root with a user with nvcc, and then separately run sudo make sysinstall after.
Yes this is exactly my case.
Also please could you make INSTALL file with install instructions...
Currently had to read Makefile to understand that "sudo make sysinstall" is the right command that does installation. There was also "sudo python setup.py install" option -- which one is better?

**Comment by scttl** [comment]
Installation instructions are spelled out in the documentation ex. this page: http://neon.nervanasys.com/docs/latest/user_guide.html#installation

Because neon is a python package calling setuptools `setup.py install` will work but by using `make` based commands you'll get dependencies handled and get neon registered with pip's package manager in the case of a system-wide install.

We actually recommend the virtualenv based install over system-wide since you can do it all as an unprivileged user (which avoids the nvcc/sudo PATH issue you're facing), makes it easier to develop/extend neon (no reinstall needed, just edit code directly), and provides isolated sandboxes on multi-user systems or if you want to run multiple versions of neon.
