### ISSUE TITLE
FAQ: can neon (or nervanagpu) be run on TX1?

### ISSUE THREAD

**Issue by hengck23** [NervanaSystems/neon#175]
This is an FAQ and not an issue.
(I am sorry if I post the FAQ in the wrong channel. Please let me know where I can post FAQ)

Can neon (or nervanagpu) be run on Jetson TX1?
Thank you very much.

**Comment by scott-gray** [comment]
Neon now can be run on the X1.  Nervanagpu development has stopped and has been been moved into neon so it wont get that update.  Neon now builds the sass kernel stubs with ptxas instead of nvcc. This allows you to specify a 64 bit address size in the 32bit binaries.   This is what was previously broken.

New kernels will be available soon to allow training and inference with very small batch sizes.  These should significantly outperform cudnn on the X1.
