### ISSUE TITLE
cuInit failed: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by Kaixhin** [NervanaSystems/neon#186]
My [`kaixhin/cuda-neon` builds](https://hub.docker.com/r/kaixhin/cuda-neon/builds/) have been failing for about a month now, and I've traced it to the fact that `make_kernels.py` is looking for a GPU. Is this required or can compilation proceed without a GPU? Stack trace below:

```make
Cloning maxas repo...
Cloning into '.venv/maxas'...

Installing maxas...

Traceback (most recent call last):
  File "neon/backends/make_kernels.py", line 24, in <module>
    import pycuda.autoinit
  File "/usr/local/lib/python2.7/dist-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.RuntimeError: cuInit failed: no CUDA-capable device is detected
make: *** [kernels] Error 1
```

**Comment by scttl** [comment]
Hi, thanks for pointing this out.

We actually have a fix already prepped internally that we'll be pushing out later this week.

We attempt to probe the GPU(s) to determine compute capability.  With this fix, if no GPU is found we will default to compute capability 5.0 instead of just failing outright.

**Comment by scttl** [comment]
We pushed the fix last night, and it looks like your [cuda-neon](https://hub.docker.com/r/kaixhin/cuda-neon/builds/) builds are again completing successfully (let us know if there are any lingering issues, and we can re-open this).
