### ISSUE TITLE
Does neno CPU backend support native C code?

### ISSUE THREAD

**Issue by jinhou** [NervanaSystems/neon#218]
Hi, I am wondered the CPU backend is implemented with python code or native C code? I am trying to run the example code with only CPU. It seemed that only one CPU core was utilized. 

Thanks
Jinlong

**Comment by yinyinl** [comment]
The CPU backend is implemented with python by wrapping numpy. And the interfaces are consistent to the GPU backend and any other backend in the future to form this MOP layer, which allows easy switch from neon.

**Comment by hanlin-nervana** [comment]
Hi Jinlong,

Since the CPU backend wraps numpy, you can install OpenBLAS (see optional packages udner http://neon.nervanasys.com/docs/latest/installation.html) to enable multi-core CPU. You would have to do the following within the neon virtual environment:
1. Install OpenBLAS (http://www.openblas.net/)
2. Reinstall and configure numpy for OpenBLAS [edit numpy's site.cfg file and link to your openblas library] 

Here are sample instructions for ubuntu OS: https://hunseblog.wordpress.com/2014/09/15/installing-numpy-and-openblas/

**Comment by tambetm** [comment]
Just a minor inconsistency between GPU and CPU backends - CPUTensor.asnumpyarray() returns shared instance (pointer), while GPUTensor.asnumpyarray() always returns a new instance (copy). I had a very hard-to-find bug regarding this.

**Comment by scttl** [comment]
Hi Tambet,

You'll be happy to know that we recently corrected this inconsistent behavior as part of: 1eda2b0

**Comment by jinhou** [comment]
Hi Hanlin,

Thanks for your reply. That means the CPU performance should be very poor in neon compared with other DL frameworks, which have dedicated CPU code for conv layers and other nn layers implementation? Do you have any plan to add optimized CPU code in your framework?

Thanks
Jinlong

**Comment by hanlin-nervana** [comment]
Hi Jinlong,

We would welcome contributions to the CPU backend. Right now we have optimized C code, but primarily for ingesting datasets and keeping the GPU fed with data.

Thanks! 

Hanlin
