### ISSUE TITLE
call model.fit() in a loop cause GPU out of memory error

### ISSUE THREAD

**Issue by mingwugmail** [NervanaSystems/neon#249]
https://groups.google.com/forum/#!topic/neon-users/Rj5INCvhx7I

while True:
  (X_train, y_train) = collect_new_dataset()
  dataset = ArrayIterator(X_train, y_train, ...)
  model.fit(dataset, optimizer=opt_gdm, num_epochs=args.epochs, cost=cost, callbacks=callbacks)
  if enough:  break

My data is not image, so I cannot use Macrobatching, which according to doc: "Currently, neon only supports macrobatching with image datasets using the ImageLoader class."

And my data is dynamically generated on the fly.

I hope Neon can provide a better set of api, e.g. as Keras do:

http://keras.io/models/model/

Thanks.

**Comment by hanlin-nervana** [comment]
There is an out-of-memory error because new buffers are being allocated at every for loop. We would not recommend this approach. 

Supporting dynamically generated data through an API is not on our near-term roadmap. Writing your custom dataset iterator however, is fairly straightforward. For a tutorial, please see https://github.com/NervanaSystems/neon_course/blob/master/03%20Writing%20your%20own%20dataset.ipynb
