### ISSUE TITLE
Cuda "streams" and parallelized multimatrix multiplication

### ISSUE THREAD

**Issue by MadcowD** [NervanaSystems/neon#294]
Hi!

I am wondering if Neon supports concurrent evaluation of matrix multiplication using CUDA streams. In other words for `A_i, B_i \in M_n(\mathbb{R})` can I evaluate `A_iB_i` for all `i \in F \subset \mathbb{N}` finite, concurrently?

Thanks

**Comment by thestew42** [comment]
Hi,

Neon does not currently support operations on a single GPU in multiple streams. However this problem sounds like it could be solved with a batched GEMM operation. The neon GPU backend supports batched GEMM, which can compute many matrix multiplications assuming they are the same size and are stored in a strided memory pattern (in this case meaning a 3d tensor). There are some limitations on how this can be applied, but it could give you some speedup since this will map all of your GEMMs to different CUDA blocks, as opposed to different streams.

-Stewart

**Comment by MadcowD** [comment]
@thestew42 Interesting! I was aware of this functionality, the interesting bit comes, at least in my case when the matrices are of different sizes. Thank's for the prompt response.
