### ISSUE TITLE
what is sass? sass is a assembled language?

### ISSUE THREAD

**Issue by Weyne168** [NervanaSystems/neon#306]
Hi, I read the code and think the core for accelerating the rate of computing is depended on  the sass files.

But, its codes is a new thing for me? whether sass is a programming language? Is there a tutorial for this language?

And, whether it likes the assembly language which is related to the cpu types?

**Comment by thestew42** [comment]
Yes many of our performance-critical GPU kernels are written in SASS rather than CUDA C. SASS is the assembly code which runs on NVIDIA GPUs. We use an assembler for the Maxwell/Pascal architecture in particular which was written by Scott Gray. There are some tutorials and explanations on the github page: https://github.com/NervanaSystems/maxas
