### ISSUE TITLE
Make file error: src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory

### ISSUE THREAD

**Issue by pantherso48** [NervanaSystems/neon#414]
Hey guys,

I'm running Ubuntu 16.04 on a VM on a Windows 10 machine.

I can clone the code and am at the recent head on the git tree but when I try to run the Make command I get the following errors. I installed the virtualenv plugin as well.

Any direction would be greatly appreciated.

make[1]: Entering directory '/usr/bin/neon/neon/backends/mklEngine'
make[1]: Leaving directory '/usr/bin/neon/neon/backends/mklEngine'
make[1]: Entering directory '/usr/bin/neon/neon/backends/mklEngine'
Building mklEngine.so...
gcc src/conv.c src/pooling.c src/relu.c src/batchNorm.c src/concat.c src/softmax.c src/MKLDNN.h -shared -o mklEngine.so -std=c99 -O3 -I/usr/bin/neon//include -L/usr/bin/neon//lib -Wl,-rpath=/usr/bin/neon//lib -fopenmp -lmklml_gnu -fPIC -march=native -g -liomp5
In file included from src/conv.c:15:0:
src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory
compilation terminated.
In file included from src/pooling.c:15:0:
src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory
compilation terminated.
In file included from src/relu.c:15:0:
src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory
compilation terminated.
In file included from src/batchNorm.c:15:0:
src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory
compilation terminated.
In file included from src/concat.c:15:0:
src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory
compilation terminated.
In file included from src/softmax.c:16:0:
src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory
compilation terminated.
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:1:0: fatal error: can’t create precompiled header mklEngine.so: Permission denied
 /* Copyright (C) 1991-2016 Free Software Foundation, Inc.
 ^
compilation terminated.
Makefile:37: recipe for target 'mklEngine.so' failed
make[1]: * [mklEngine.so] Error 1
make[1]: Leaving directory '/usr/bin/neon/neon/backends/mklEngine'
Updating virtualenv dependencies in: .venv2...
Running virtualenv with interpreter /usr/bin/python2.7
Traceback (most recent call last):
  File "/home/rmcarper/.local/lib/python2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/home/rmcarper/.local/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/home/rmcarper/.local/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/rmcarper/.local/lib/python2.7/site-packages/virtualenv.py", line 1110, in install_python
    mkdir(lib_dir)
  File "/home/rmcarper/.local/lib/python2.7/site-packages/virtualenv.py", line 323, in mkdir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/bin/neon/.venv2'
Makefile:122: recipe for target '.venv2/bin/activate' failed
make: * [.venv2/bin/activate] Error 1

**Comment by wei-v-wang** [comment]
This usually points to a MKL download problem. 

Do you see a file named mklml_lnx_2018.0.20170908.tgz under neon directory?

**Comment by pantherso48** [comment]
Not seeing it in the GUI or terminal, where can I get it to add to my project?



![image](https://user-images.githubusercontent.com/13629866/32462005-e46fbc24-c305-11e7-8294-2268ff1beabc.png)

**Comment by wei-v-wang** [comment]
The mklml_lnx_2018.0.20170908.tgz is supposed to be automatically downloaded (when there is good internet configuration) from https://github.com/01org/mkl-dnn/releases/download/v0.10/mklml_lnx_2018.0.20170908.tgz  

If for some reason, the file has to be manually downloaded and put to the ROOT of neon directory (in your case /usr/bin/neon). Please also manually unzip it (tar xvf mklml_lnx_2018.0.20170908.tgz)

Then, please comment out the following two lines from prepare_mkl.sh 

61       wget --no-check-certificate -P $DST $MKLURL -O $DST/$ARCHIVE_BASENAME > /dev/null 2>&1
 62       tar -xzf $DST/$ARCHIVE_BASENAME -C $DST > /dev/null 2>&1

So that becomes 
61       #wget --no-check-certificate -P $DST $MKLURL -O $DST/$ARCHIVE_BASENAME > /dev/null 2>&1
 62       #tar -xzf $DST/$ARCHIVE_BASENAME -C $DST > /dev/null 2>&1

type "make clean && make" after you verify that you have the following under neon ROOT directory

/usr/bin/neon/mklml_lnx_2018.0.20170908$ ls  * 
license.txt

include:
i_malloc.h  mkl_cblas.h  mkl_dnn_types.h  mkl_lapack.h   mkl_trans.h  mkl_version.h      mkl_vml_functions.h  mkl_vml_types.h    mkl_vsl_functions.h  mkl_vsl_types.h
mkl_blas.h  mkl_dnn.h    mkl_lapacke.h    mkl_service.h  mkl_types.h  mkl_vml_defines.h  mkl_vml.h            mkl_vsl_defines.h  mkl_vsl.h

lib:
libiomp5.so  libmklml_gnu.so  libmklml_intel.so

**Comment by pantherso48** [comment]
That worked well, thank you!!!
