### ISSUE TITLE
MKL not supported For Mac Osx

### ISSUE THREAD

**Issue by ZE0TRON** [NervanaSystems/neon#429]
By following the steps in ReadMe.md we can end up with the error 
`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/neon/backends/mklEngine/mklEngine.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00`
while using python3. 
ReadMe.md can be updated with the info that MKL is not supported For Mac Osx so while using python3 people should use -b cpu or -b gpu parameters(default is mkl).

**Comment by wei-v-wang** [comment]
@ZE0TRON Currently neon with Intel Architecture optimizations (w/ Intel MKL Integration) do not support MacOS -- although Intel Math Kernel Library (MKL) already supports MacOS. 
The reason you saw the above was because neon by default download Linux MKL, while MacOS MKL is available from a similar URL https://github.com/01org/mkl-dnn/releases/download/v0.11/mklml_mac_2018.0.1.20171007.tgz  (you can change prepare_mkl.sh or download_mkl.sh) but compiling on MacOS that supports Clang OpenMP is probably the hurdle

**Comment by wei-v-wang** [comment]
Turned out using gcc might work on Mac for enabling MKL. Please stay tuned.
