### ISSUE TITLE
GPU backend max operator not implemented for transpose 

### ISSUE THREAD

**Issue by seba-1511** [NervanaSystems/neon#64]
Good morning,

The following code raises `TransposeCUDAMatrix` has not attribute `max`. I work with cuda-convnet, and don't know if it is also a problem with NervanaGPU. However it doesn't happen with CPU backends.

```python
gpu = gen_backend(gpu='cudanet')
b = gpu.array([1, 2, 3])
c = gpu.empty((1, 1))
c = gpu.max(b.transpose(), None, c)
```

I can try to work on that, but don't know how long it will take me. (little time lately)
Séb

**Comment by scttl** [comment]
Hi Seb,

Was able to reproduce your problem, but I'm not sure where we'd need to pass a transposed argument to `max()`?  If you're taking this over all axes you can pass in `b` as is and get the same result.  Or if it was over one axis for a 2D input, you can get the same result by choosing the other axis of an expected transposed input.

Updating the cc2 code to support transposed arguments would be a fair bit of effort (lots of other operations are similarly impacted), and we're likely going to deprecate the cc2 backend anyway.  We may end up backporting support for older cards into nervanagpu.

Interestingly the code doesn't work with nervanagpu as written either, but this is due to `b` being a vector and `c` a 2D matrix.  With `b` a 1x3 2D matrix it works.

**Comment by seba-1511** [comment]
Indeed, this is interesting. 

I ran into this problem when working with the predictions coming out of a net, but it seems that maxing on the other axis and then transposing would probably do the job. Anyway, thought that I'd point that out.
