### ISSUE TITLE
About activation's back propagation  code

### ISSUE THREAD

**Issue by xiuxiazhang** [NervanaSystems/neon#65]
Recently I am reading the neon code. I found that,  in back propagation process, apply_derivative is not called by tanh, sigmoid, logistic activation class. 
Instead all these functions use backend.multiply(error, pre_act, out=error) to compute deltas.

I am a little confused, it's different from my comprehension about textbook or Jack Bouvrie's paper.  
In his paper, he use  derivative  to compute  deltas.

Thanks,
Xiuxia

**Comment by scttl** [comment]
Hi Xiuxia,

That's right there's no explicit `apply_derivative` during the bprop call as the derivatives for these activations are pre-computed and stored during the *forward* pass because we have all the info we need to compute them at that time (this allows us to speed things up and use fewer buffers).  

As an example the tanh(x) derivative is 1 - tanh^2(x), so if you look in `fprop_func()` in tanh.py you'll see that after computing the value for tanh on the `inputs` and storing it in `outputs`, we're also squaring this output value, subtracting 1 from it, and storing this back in `inputs` which we'll utilize in the bprop phase.  If you look in say `layers/fully_connected.py` you'll see that during `fprop()` and `bprop()` calls we're passing in `self.pre_act` for the `inputs` parameter I mentioned earlier.

Hope that clears things up for you.
