### ISSUE TITLE
Inputting new images into a trained ImageCaption model

### ISSUE THREAD

**Issue by EricZeiberg** [NervanaSystems/neon#90]
I ran the image classification script on the flickr8k dataset and it finished training and outputted a `.pickle` file. How do I now run it on arbitrary images and have it generate sentences for those?

I know for NeuralTalk I had to run a script to extract features from the image, but how does it work for this library?

**Comment by jcoreyes** [comment]
It's going to take some work to get it working on new images but there are multiple ways to do it. You can use the VGG model from NeuralTalk to get the features, then create a new dataset iterator in Neon based on imagecaption.py which just loads in the images. We're working on creating a script to convert caffee models to neon models so that you'd be able to run a pretrained VGG from caffee in Neon.

**Comment by EricZeiberg** [comment]
Can you elaborate more on the NeuralTalk VGG model option? I understand how to extract the features from the image, but then how do I pipe it back into the imagecaption file?

**Comment by jcoreyes** [comment]
This will have most of what you need https://github.com/NervanaSystems/neon/blob/master/neon/data/imagecaption.py. In read_images(), load in the VGG features from NeuralTalk instead of the presaved ones. In ImageCaptionTest, you can remove the sentence loading code in the constructor and the ref sentence loading in the iter.
