### ISSUE TITLE
LSTM text generation example doesn't work

### ISSUE THREAD

**Issue by chetan51** [NervanaSystems/neon#91]
Once training is complete, I see this error (instead of it generating text):

	Development/neon - [master●] » ./examples/text_generation_lstm.py
	Epoch 0   [Train |████████████████████| 1004/1004 batches, 2.73 cost, 2478.91s][Validation 2.37 cost, 137.46s]
	Epoch 1   [Train |████████████████████| 1004/1004 batches, 2.10 cost, 2041.21s][Validation 2.18 cost, 93.31s]
	Epoch 2   [Train |████████████████████| 1004/1004 batches, 1.96 cost, 1762.60s][Validation 2.13 cost, 97.32s]
	Epoch 3   [Train |████████████████████| 1004/1004 batches, 1.89 cost, 1955.90s][Validation 2.10 cost, 123.01s]
	Epoch 4   [Train |████████████████████| 1004/1004 batches, 1.85 cost, 2289.69s][Validation 2.09 cost, 125.11s]
	Epoch 5   [Train |████████████████████| 1004/1004 batches, 1.82 cost, 2324.10s][Validation 2.08 cost, 125.85s]
	Epoch 6   [Train |████████████████████| 1004/1004 batches, 1.80 cost, 2310.14s][Validation 2.08 cost, 126.98s]
	Epoch 7   [Train |████████████████████| 1004/1004 batches, 1.79 cost, 2334.25s][Validation 2.07 cost, 128.41s]
	Epoch 8   [Train |████████████████████| 1004/1004 batches, 1.77 cost, 2326.02s][Validation 2.07 cost, 128.01s]
	Epoch 9   [Train |████████████████████| 1004/1004 batches, 1.76 cost, 2342.65s][Validation 2.07 cost, 125.19s]
	Traceback (most recent call last):
	  File "./examples/text_generation_lstm.py", line 128, in <module>
	    x[pred, 0] = 1
	  File "/Users/Chetan/Dropbox/Development/neon/neon/backends/nervanacpu.py", line 146, in __setitem__
	    self.__getitem__(key)._assign(value)
	  File "/Users/Chetan/Dropbox/Development/neon/neon/backends/nervanacpu.py", line 211, in _assign
	    self.set(value)
	  File "/Users/Chetan/Dropbox/Development/neon/neon/backends/nervanacpu.py", line 238, in set
	    self._tensor[:] = value
	ValueError: cannot slice a 0-d array

Attached is the generated `rnn_text_gen.pickle` file (but renamed as a .png so I could upload it here).

![rnn_text_gen](https://cloud.githubusercontent.com/assets/310282/9884347/17a1d752-5b94-11e5-9d28-9c5e19cfecac.png)

**Comment by jcoreyes** [comment]
On line 128 in that file try wrapping pred as an int so use x[int(pred), 0] = 1

**Comment by chetan51** [comment]
@jcoreyes Thanks, I sent a pull request to that effect.

**Comment by NeuroCampos** [comment]
I just cloned the repo today and have the following error (instead of generating text) on the text_generation_lstm.py example.  I'm running this on a TitanX in a DIGITS DevBox.

(.venv)michael@BlackBox:~/code/neon4/neon/examples$ ./text_generation_lstm.py
Network Layers:
	LSTM LstmLayer
	Linear Layer 'LinearLayer': 512 inputs, 67 outputs
	Bias Layer 'BiasLayer': size 67
	Activation Layer 'ActivationLayer': Softmax

Epoch 0   [Train |████████████████████| 1004/1004 batches, 2.78 cost, 67.14s][Validation 2.36 cost, 3.05s]
Epoch 1   [Train |████████████████████| 1004/1004 batches, 2.10 cost, 67.41s][Validation 2.20 cost, 3.07s]
Epoch 2   [Train |████████████████████| 1004/1004 batches, 1.96 cost, 67.31s][Validation 2.13 cost, 3.05s]
Epoch 3   [Train |████████████████████| 1004/1004 batches, 1.89 cost, 67.51s][Validation 2.10 cost, 3.07s]
Epoch 4   [Train |████████████████████| 1004/1004 batches, 1.85 cost, 67.37s][Validation 2.09 cost, 3.07s]
Epoch 5   [Train |████████████████████| 1004/1004 batches, 1.82 cost, 67.07s][Validation 2.08 cost, 3.06s]
Epoch 6   [Train |████████████████████| 1004/1004 batches, 1.80 cost, 67.40s][Validation 2.08 cost, 3.06s]
Epoch 7   [Train |████████████████████| 1004/1004 batches, 1.78 cost, 67.47s][Validation 2.08 cost, 3.07s]
Epoch 8   [Train |████████████████████| 1004/1004 batches, 1.77 cost, 67.28s][Validation 2.08 cost, 3.05s]
Epoch 9   [Train |████████████████████| 1004/1004 batches, 1.76 cost, 67.56s][Validation 2.07 cost, 3.07s]
Traceback (most recent call last):
  File "./text_generation_lstm.py", line 120, in <module>
    y = model.fprop(x)
  File "/home/michael/code/neon4/neon/neon/models/model.py", line 202, in fprop
    x = l.fprop(x, inference)
  File "/home/michael/code/neon4/neon/neon/layers/recurrent.py", line 287, in fprop
    self.init_buffers(inputs)
  File "/home/michael/code/neon4/neon/neon/layers/recurrent.py", line 95, in init_buffers
    self.xs = get_steps(inputs, self.in_shape)
AttributeError: 'LSTM' object has no attribute 'in_shape'



I figure that it either has something to do with skipped/different configuration steps relative to what happens with model.fit, or maybe it has to do with the reduced number of timesteps in the text generation portion of the code.

**Comment by yinyinl** [comment]
We have a fix to this problem and will release it very soon. Meanwhile, please continue looking at our other RNN-related examples for neon RNN functionalities. Thank you.

**Comment by NeuroCampos** [comment]
Tried it and it works!  Thanks @yinyinl
